// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCptMA_R3t4IaK2cpHa6yrSzRXPis_mhtI',
    appId: '1:556465108102:web:d7c242c59e71dd747ecd07',
    messagingSenderId: '556465108102',
    projectId: 'ecommerce-4e89d',
    authDomain: 'ecommerce-4e89d.firebaseapp.com',
    storageBucket: 'ecommerce-4e89d.appspot.com',
    measurementId: 'G-Y82DTF9D21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU060iBYnu9uO1DTSGX__uah4xF4UbeXI',
    appId: '1:556465108102:android:7cf8d322fd0efc787ecd07',
    messagingSenderId: '556465108102',
    projectId: 'ecommerce-4e89d',
    storageBucket: 'ecommerce-4e89d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxYytMQgq8WAt9ULvkvRUfv1277TWDMw',
    appId: '1:556465108102:ios:96e503d4f7a56e5f7ecd07',
    messagingSenderId: '556465108102',
    projectId: 'ecommerce-4e89d',
    storageBucket: 'ecommerce-4e89d.appspot.com',
    androidClientId: '556465108102-d5an04o4jeum7debgchl54ifeld3clpd.apps.googleusercontent.com',
    iosClientId: '556465108102-26k3ec79ln7loo8qvmr1ds1pi3ced3j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhxYytMQgq8WAt9ULvkvRUfv1277TWDMw',
    appId: '1:556465108102:ios:96e503d4f7a56e5f7ecd07',
    messagingSenderId: '556465108102',
    projectId: 'ecommerce-4e89d',
    storageBucket: 'ecommerce-4e89d.appspot.com',
    androidClientId: '556465108102-d5an04o4jeum7debgchl54ifeld3clpd.apps.googleusercontent.com',
    iosClientId: '556465108102-26k3ec79ln7loo8qvmr1ds1pi3ced3j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
